# 一，加载数据

In [17]:
#引入数据库
import pandas as pd
import numpy as np
from pandas import DataFrame,Series
import matplotlib.pyplot as plt

#读取数据

df = pd.read_excel('D:\order\DATA.csv')
df.head()

,id,门店编号,店铺名称,门店统一码（一家店双平台统一码一样）,渠道名称,日期（分析的日期）,实际收入,营业额,顾客实付,客单价,...,当日消耗,差评解决数,中评数,中评解决数,评分,推广账号余额,充值金额,省,市,区
0,21765.0,7.791686e+06,酱汁满串烧烤集市(莲花店),JZMC_000018,美团,2019-12-01,1931.73,5381.62,0.00,75.80,...,200.02,0.0,0.0,1.0,4.7,NaN,NaN,江苏省,苏州市,吴中区
1,21766.0,2.001031e+09,黑牛东（前网新村店）,HND_000007,饿了么,2019-12-01,47.14,87.00,70.64,23.55,...,0.00,0.0,0.0,0.0,4.3,NaN,NaN,浙江省,温州市,鹿城区
2,21767.0,7.898976e+06,酱汁满串烧烤集市（国美店）,JZMC_000006,美团,2019-12-01,2021.04,5058.70,0.00,67.45,...,305.45,1.0,0.0,0.0,4.6,NaN,NaN,北京市,北京市,朝阳区
3,21768.0,7.156277e+06,酱汁满串烧烤集市（龙汇路店）,JZMC_000009,美团,2019-12-01,2345.45,5565.60,0.00,77.30,...,304.71,0.0,0.0,0.0,4.3,NaN,NaN,上海市,上海市,浦东新区
4,21769.0,7.388042e+06,酱汁满串烧烤集市（七莘路店）,JZMC_000010,美团,2019-12-01,765.59,1630.60,0.00,81.53,...,100.01,0.0,0.0,0.0,4.3,NaN,NaN,上海市,上海市,闵行区

# 二，提取数据

# 2.1，统计出本月度总营业额/饿了么总营业额/美团总营业额

In [18]:
turnover = df[['渠道名称','营业额']]
res_mie = turnover.query('渠道名称 == "美团"') 
res_e = turnover.query('渠道名称 == "饿了么"')
turnover

      渠道名称          营业额
0       美团      5381.62
1      饿了么        87.00
2       美团      5058.70
3       美团      5565.60
4       美团      1630.60
...    ...          ...
23787  饿了么         0.00
23788  饿了么         0.00
23789  饿了么         0.00
23790  饿了么         0.00
23791  NaN  37683837.27

[23792 rows x 2 columns]

In [19]:
#总营业额
k = 0
for i in turnover['营业额']:
    k = k+i
print(k)

75367674.53999975

In [20]:
#饿了么
a = 0 
for i in res_e['营业额']:
    a = a+i
print(a)

30293752.620000035

In [21]:
#美团
b = 0 
for i in res_mie['营业额']:
    b = b+i
print(b)

7390084.65000001

# 2.2 统计饿了么下单转化最高的前五家店铺名称

In [22]:
list_e = df[['店铺名称','渠道名称','下单转化率']]
list_elm = list_e.query('渠道名称 == "饿了么"')
#list_elm
name = list_elm.sort_values(['下单转化率'], ascending = False)# 降序
a = name.head()
a
#a.plot()

                 店铺名称 渠道名称  下单转化率
14671      酱暖七点粥(晒布店)  饿了么  100.0
12746      禧尝冒菜(合兴路店)  饿了么   66.7
7737     厨子与辣子(金枫国际店)  饿了么   62.5
15631           横向南街店  饿了么   53.8
458    大渝盆鲜·毛血旺(长寿路店)  饿了么   53.8

# 2.3 统计美团本月所有店铺的平均客单价/客单价前五的店铺名称

In [23]:
store = df.query('渠道名称 == "美团"')[['店铺名称','客单价']]
store_ranking = store.sort_values(['客单价'], ascending = False)# 降序
#客单价前五的店铺名称
store_ranking.head()

                       店铺名称     客单价
11633             大渝盆鲜（中山店）  300.56
12166        酱汁满串烧烤集市(通达路店)  260.90
18346        酱汁满串烧烤集市(通达路店)  184.11
1305   一馍一秧·正宗西北民食(苏州万枫家园店)  177.20
17592        酱汁满串烧烤集市(通达路店)  177.10

In [24]:
#总价
a = 0 
for i in store['客单价']:
    a = a+i
print(a)

#平均客单价
average = a/len(store)
average

277287.5999999986

38.70029309141641

# 2.4 分别统计饿了么和美团差评最多的五家店铺名称

In [25]:
review = df[['店铺名称','渠道名称','差评数']]
review

                 店铺名称 渠道名称  差评数
0       酱汁满串烧烤集市(莲花店)   美团  0.0
1          黑牛东（前网新村店）  饿了么  0.0
2       酱汁满串烧烤集市（国美店）   美团  0.0
3      酱汁满串烧烤集市（龙汇路店）   美团  0.0
4      酱汁满串烧烤集市（七莘路店）   美团  0.0
...               ...  ...  ...
23787      禧尝冒菜(团结村店)  饿了么  0.0
23788    酱暖七点粥(无锡滨湖店)  饿了么  0.0
23789      酱暖七点粥(城阳店)  饿了么  0.0
23790     酱暖七点粥（步行街店）  饿了么  0.0
23791             NaN  NaN  NaN

[23792 rows x 3 columns]

In [26]:
review_mei = review.query('渠道名称 == "美团"')
review_mei.dropna()
# len(review_mei['差评数'].unique())
review_mei.drop_duplicates(['差评数'],keep='last').sort_values(['差评数'], ascending = False).head()# 降序

               店铺名称 渠道名称  差评数
6992   厨子与辣子（肇嘉浜路店）   美团  6.0
18785    厨子与辣子（北蔡店）   美团  5.0
16428    厨子与辣子（北蔡店）   美团  4.0
18771  鸡小酱鸡公煲（岚清路店）   美团  3.0
18791     黑牛东（李子园店）   美团  2.0

# 2.5 统计本月店铺的平均消耗金额/消耗最多的前五家店铺以及所在的省市区

In [27]:
average = df[['店铺名称', '当日消耗', '省', '市', '区', '渠道名称']]
average_g = average.groupby(['店铺名称'], as_index=False)
df_sum = average_g.sum().reset_index()
df_mean = average_g.mean().reset_index()
df_sum['sum'] = df_sum['当日消耗']
df_mean['mean'] = df_mean['当日消耗']

average1 = average.drop_duplicates(['店铺名称'])
average2 = pd.merge(average1, df_sum, how='left', left_on='店铺名称', right_on='店铺名称')
average3 = pd.merge(average2, df_mean, how='left', left_on='店铺名称', right_on='店铺名称')
average4 = average3[['店铺名称', 'sum', 'mean', '省', '市', '区', '渠道名称']].sort_values(by=['sum'], ascending=0)
average4.head()

                店铺名称       sum        mean    省    市     区 渠道名称
22   酱汁满串烧烤集市(华江支路店)  17037.17  274.793065  上海市  上海市   嘉定区   美团
147     厨子与辣子(肇嘉浜路店)  14297.73  461.217097  上海市  上海市   徐汇区  饿了么
489      麻选食记(肇嘉浜路店)  14296.43  183.287564  上海市  上海市   徐汇区  饿了么
139      厨子与辣子（八佰伴店）  12963.60  418.180645  上海市  上海市  浦东新区  饿了么
286   酱汁满串烧烤集市(定西路店)  12205.40  393.722581  上海市  上海市   长宁区  饿了么

# 2.6 统计上海总共有多少家店铺，上海哪个区的哪个店的生意最好（前五家）

In [97]:
shanghai = df[['店铺名称','省','区','实际收入']]
shanghai_1 = shanghai.dropna().query('省 == "上海市"')
len(shanghai_1)
# len(shanghai_1['店铺名称'].unique())#统计共有多少加店铺

8077

In [98]:
shanghai_1.drop_duplicates(['店铺名称']).sort_values(['实际收入'], ascending = False).iloc[[0]]#店铺生意最好的一家

                店铺名称    省    区     实际收入
294  酱汁满串烧烤集市(肇嘉浜路店)  上海市  徐汇区  9028.13

# 2.7 统计给我们带来收入最高的五家店的名称,消耗总额,省，市，区

In [106]:
earnings = df[['店铺名称', '当日消耗', '省', '市', '区']]
earnings_g = average.groupby(['店铺名称'], as_index=False)
earnings_sum = earnings_g.sum().reset_index()
earnings_mean = earnings_g.mean().reset_index()
earnings_sum['sum'] = earnings_sum['当日消耗']

earnings1 = earnings.drop_duplicates(['店铺名称'])
earnings2 = pd.merge(earnings1, earnings_sum, how='left', left_on='店铺名称', right_on='店铺名称')
earnings3 = pd.merge(earnings2, earnings_mean, how='left', left_on='店铺名称', right_on='店铺名称')
earnings4 = earnings3[['店铺名称', 'sum', '省', '市', '区']].sort_values(by=['sum'], ascending=0)
earnings4.head()

                店铺名称       sum    省    市     区
22   酱汁满串烧烤集市(华江支路店)  17037.17  上海市  上海市   嘉定区
147     厨子与辣子(肇嘉浜路店)  14297.73  上海市  上海市   徐汇区
489      麻选食记(肇嘉浜路店)  14296.43  上海市  上海市   徐汇区
139      厨子与辣子（八佰伴店）  12963.60  上海市  上海市  浦东新区
286   酱汁满串烧烤集市(定西路店)  12205.40  上海市  上海市   长宁区